# Generated by Django 5.0.6 on 2026-05-06 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_age', models.IntegerField(blank=True, help_text='Edad minima', null=True)),
                ('max_age', models.IntegerField(blank=True, help_text='Edad maxima', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'config_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'config_disciplines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'config_sexes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_time_based', models.BooleanField(default=True, help_text='Si el resultado se mide en tiempo')),
                ('is_distance_based', models.BooleanField(default=False, help_text='Si el resultado se mide en distancia')),
                ('is_points_based', models.BooleanField(default=False, help_text='Si el resultado se mide en puntos')),
                ('unit', models.CharField(default='segundos', help_text='Unidad de medida', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='config.discipline')),
            ],
            options={
                'db_table': 'config_event_types',
                'ordering': ['discipline', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FunctionalClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='config.discipline')),
            ],
            options={
                'db_table': 'config_functional_classifications',
                'ordering': ['discipline', 'code'],
                'unique_together': {('code', 'discipline')},
            },
        ),
    ]
