# Generated by Django 5.0.6 on 2026-05-06 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bib_number', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competitions_athlete_events',
                'ordering': ['tournament_event', 'bib_number'],
            },
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('best_mark', models.CharField(blank=True, max_length=100)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('record_type', models.CharField(blank=True, choices=[('tournament', 'Record del Torneo'), ('national', 'Record Nacional'), ('american', 'Record Americano'), ('world', 'Record Mundial')], max_length=20)),
                ('is_dnf', models.BooleanField(default=False, help_text='Did Not Finish')),
                ('is_dns', models.BooleanField(default=False, help_text='Did Not Start')),
                ('is_dq', models.BooleanField(default=False, help_text='Disqualified')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competitions_final_results',
                'ordering': ['tournament_event', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_head', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'competitions_judge_assignments',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('withdrawn', 'Retirada')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('exempt', 'Exento')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'competitions_registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Resultado numerico', max_digits=10, null=True)),
                ('mark', models.CharField(blank=True, help_text='Marca textual (ej: 1:23.45)', max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('wind', models.DecimalField(blank=True, decimal_places=1, help_text='Velocidad del viento', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'competitions_results',
                'ordering': ['athlete_event', 'attempt_number'],
            },
        ),
    ]
