# Generated by Django 5.0.6 on 2026-05-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteevent',
            name='tournament_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_events', to='tournaments.tournamentevent'),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.athlete'),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='tournament_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='tournaments.tournamentevent'),
        ),
    ]
