# Generated by Django 5.0.6 on 2026-05-06 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='tournament_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='tournaments.tournamentevent'),
        ),
        migrations.AddField(
            model_name='registration',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.athlete'),
        ),
        migrations.AddField(
            model_name='registration',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.institution'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='athleteevent',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_events', to='competitions.registration'),
        ),
        migrations.AddField(
            model_name='result',
            name='athlete_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.athleteevent'),
        ),
        migrations.AddField(
            model_name='result',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='finalresult',
            unique_together={('tournament_event', 'athlete')},
        ),
        migrations.AlterUniqueTogether(
            name='judgeassignment',
            unique_together={('tournament_event', 'judge')},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('tournament', 'athlete')},
        ),
    ]
