# Generated by Django 5.0.6 on 2026-05-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_initial'),
        ('tournaments', '0003_athlete_document_number_athlete_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('withdrawn', 'Retirada'), ('dnf', 'DNF'), ('dq', 'Descalificado')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='athleteevent',
            unique_together={('tournament_event', 'registration')},
        ),
    ]
