# Generated by Django 5.0.6 on 2026-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_athleteevent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='medical_certificate',
            field=models.FileField(blank=True, help_text='Certificado medico apto', null=True, upload_to='registrations/medical/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Comprobante de pago', null=True, upload_to='registrations/payments/'),
        ),
    ]
