# Generated by Django 5.0.6 on 2026-05-06 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('classification_status', models.CharField(choices=[('provisional', 'Provisoria'), ('confirmed', 'Confirmada')], default='provisional', max_length=20)),
                ('classification_notes', models.TextField(blank=True)),
                ('classification_date', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('medical_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tournaments_athletes',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialties', models.TextField(blank=True, help_text='Especialidades del entrenador')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tournaments_coaches',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/')),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tournaments_institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario Institucion',
                'db_table': 'tournaments_institution_users',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('registration_open', 'Inscripcion Abierta'), ('registration_closed', 'Inscripcion Cerrada'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('registration_opens', models.DateTimeField()),
                ('registration_closes', models.DateTimeField()),
                ('tournament_start', models.DateTimeField()),
                ('tournament_end', models.DateTimeField()),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='Costo de inscripcion por atleta', max_digits=10)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('rules', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tournaments_tournaments',
                'ordering': ['-tournament_start'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('scheduled_date', models.DateTimeField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('venue_detail', models.CharField(blank=True, help_text='Pista, sector, etc.', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En Curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tournaments_tournament_events',
                'ordering': ['scheduled_date', 'name'],
            },
        ),
    ]
