# Generated by Django 5.0.6 on 2026-05-06 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='classified_by',
            field=models.ForeignKey(blank=True, help_text='Oficial que confirmo la clasificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='functional_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='config.functionalclassification'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.sex'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='tournaments.coach'),
        ),
        migrations.AddField(
            model_name='coach',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='tournaments.institution'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='tournaments.institution'),
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tournaments.institution'),
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='categories',
            field=models.ManyToManyField(related_name='tournaments', to='config.category'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='disciplines',
            field=models.ManyToManyField(related_name='tournaments', to='config.discipline'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to='tournaments.institution'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sexes',
            field=models.ManyToManyField(related_name='tournaments', to='config.sex'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.category'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.discipline'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.eventtype'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='functional_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.functionalclassification'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.sex'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.tournament'),
        ),
    ]
