# Generated by Django 5.0.6 on 2026-05-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='document_type',
            field=models.CharField(choices=[('dni', 'DNI'), ('passport', 'Pasaporte'), ('le', 'Libreta de Enrolamiento'), ('lc', 'Libreta Civica'), ('other', 'Otro')], default='dni', max_length=20),
        ),
        migrations.AddField(
            model_name='coach',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='document_type',
            field=models.CharField(choices=[('dni', 'DNI'), ('passport', 'Pasaporte'), ('le', 'Libreta de Enrolamiento'), ('lc', 'Libreta Civica'), ('other', 'Otro')], default='dni', max_length=20),
        ),
    ]
