# Generated by Django 5.0.6 on 2026-05-07 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('tournaments', '0003_athlete_document_number_athlete_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentevent',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.discipline'),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.eventtype'),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='functional_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.functionalclassification'),
        ),
    ]
