# Generated by Django 5.0.6 on 2026-05-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('tournaments', '0004_alter_tournamentevent_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='functional_classifications',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='config.functionalclassification'),
        ),
    ]
