# Generated by Django 5.0.6 on 2026-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_functional_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='athlete',
            name='address_country',
            field=models.CharField(blank=True, default='Argentina', help_text='Pais de residencia', max_length=100),
        ),
        migrations.AddField(
            model_name='athlete',
            name='address_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='athlete',
            name='address_street',
            field=models.CharField(blank=True, help_text='Direccion (calle y numero)', max_length=300),
        ),
        migrations.AddField(
            model_name='athlete',
            name='guardian_address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='athlete',
            name='guardian_address_country',
            field=models.CharField(blank=True, default='Argentina', max_length=100),
        ),
        migrations.AddField(
            model_name='athlete',
            name='guardian_address_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='athlete',
            name='guardian_address_street',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='athlete',
            name='guardian_document_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='athlete',
            name='guardian_document_type',
            field=models.CharField(blank=True, choices=[('dni', 'DNI'), ('passport', 'Pasaporte'), ('le', 'Libreta de Enrolamiento'), ('lc', 'Libreta Civica'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='athlete',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='athlete',
            name='guardian_name',
            field=models.CharField(blank=True, help_text='Nombre completo del adulto responsable', max_length=300),
        ),
        migrations.AddField(
            model_name='athlete',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='athlete',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefono del atleta', max_length=20),
        ),
    ]
