# Generated by Django 5.0.6 on 2026-06-02 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('tournaments', '0006_add_athlete_address_guardian_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='field_classification',
            field=models.ForeignKey(blank=True, help_text='Clasificacion funcional de campo (F)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_athletes', to='config.functionalclassification'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='track_classification',
            field=models.ForeignKey(blank=True, help_text='Clasificacion funcional de pista (T)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_athletes', to='config.functionalclassification'),
        ),
    ]
