# Generated by Django 5.0.6 on 2026-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_add_track_field_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
