# Generated by Django 5.0.6 on 2026-06-02 19:24
from django.db import migrations


def create_missing_athlete_profiles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Athlete = apps.get_model('tournaments', 'Athlete')
    for user in User.objects.filter(role='athlete'):
            Athlete.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_athlete_date_of_birth'),
    ]

    operations = [
        migrations.RunPython(create_missing_athlete_profiles, elidable=True),
    ]
