# Generated by Django 5.0.6 on 2026-06-11 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('tournaments', '0009_create_missing_athlete_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='head_judge',
            field=models.ForeignKey(blank=True, help_text='Juez principal del torneo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_as_head_judge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_events_per_athlete',
            field=models.IntegerField(default=0, help_text='0 = sin limite'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tournament_events', to='config.category'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='functional_classifications',
            field=models.ManyToManyField(blank=True, related_name='tournament_events', to='config.functionalclassification'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='sexes',
            field=models.ManyToManyField(blank=True, related_name='tournament_events', to='config.sex'),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.category'),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config.sex'),
        ),
    ]
