# Generated by Django 5.0.6 on 2026-06-12 22:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournament_head_judge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='can_organize',
            field=models.BooleanField(default=False, help_text='Puede crear torneos (previo pago)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='organized_until',
            field=models.DateField(blank=True, help_text='Vencimiento del permiso para organizar torneos', null=True),
        ),
        migrations.CreateModel(
            name='OrganizationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto abonado', max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField(help_text='Inicio de vigencia')),
                ('valid_until', models.DateField(help_text='Fin de vigencia')),
                ('notes', models.TextField(blank=True, help_text='Observaciones')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tournaments.institution')),
                ('paid_by', models.ForeignKey(blank=True, help_text='Admin que registró el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournaments_organization_payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
