# Generated by Django 5.0.6 on 2026-06-12 22:31

from django.db import migrations


def migrate_admin_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Institution = apps.get_model('tournaments', 'Institution')
    InstitutionUser = apps.get_model('tournaments', 'InstitutionUser')
    for user in User.objects.filter(role='admin'):
        if InstitutionUser.objects.filter(user=user).exists():
            inst_user = InstitutionUser.objects.get(user=user)
            inst = inst_user.institution
            inst.can_organize = True
            inst.save(update_fields=['can_organize'])
        else:
            name = user.first_name or user.email.split('@')[0]
            short_name = user.last_name or ''
            inst = Institution.objects.create(
                name=name,
                short_name=short_name,
                can_organize=True,
            )
            InstitutionUser.objects.create(
                institution=inst,
                user=user,
                position='Administrador',
            )
        user.role = 'institution'
        user.save(update_fields=['role'])


def reverse_migration(apps, schema_editor):
    # Irreversible: no tracking of which users were originally admin.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_institution_can_organize_institution_organized_until_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_admin_users, reverse_migration),
    ]
