# Generated by Django 5.0.6 on 2026-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_migrate_admin_users_to_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='cud_file',
            field=models.FileField(blank=True, help_text='Certificado Unico de Discapacidad (CUD)', null=True, upload_to='athletes/cud/'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='athletes/profiles/'),
        ),
    ]
