# Generated by Django 5.0.6 on 2026-06-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_athlete_cud_file_athlete_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Institución activa (visible en listados)'),
        ),
    ]
