# Generated by Django 6.0.6 on 2026-08-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_institution_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentevent',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Prueba oficial del programa (con inscriptos) tras cerrar la inscripcion'),
        ),
    ]
