# Generated by Django 6.0.6 on 2026-08-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_tournamentevent_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentevent',
            name='call_time',
            field=models.TimeField(blank=True, help_text='Hora de camara de llamada', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Hora de la prueba', null=True),
        ),
    ]
