# Generated by Django 6.0.6 on 2026-08-03 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_tournaments_as_paid(apps, schema_editor):
    Tournament = apps.get_model('tournaments', 'Tournament')
    Tournament.objects.update(payment_status='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_tournamentevent_call_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='Admin que habilito el torneo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_payments_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto abonado por el servicio del torneo', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se registro el pago', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Observaciones del pago'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Habilitado')], default='pending', help_text='Habilitacion del torneo tras el pago del servicio', max_length=20),
        ),
        migrations.RunPython(mark_existing_tournaments_as_paid, migrations.RunPython.noop),
    ]
