# Generated by Django 5.0.6 on 2026-08-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_tournament_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='use_bibs',
            field=models.BooleanField(default=True, help_text='El torneo utiliza pecheras numeradas (dorsales)'),
        ),
    ]
