# Generated by Django 5.0.6 on 2026-08-30 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_tournament_use_bibs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Opcional: institucion que organiza (no condiciona la creacion del torneo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_tournaments', to='tournaments.institution'),
        ),
    ]
